### ISSUE TITLE
不支持非 xxx.github.io 项目，GitHub Pages 加载 static 文件路径出错

### ISSUE THREAD

**Issue by JimmyLv** [bingoogolapple/bga_issue_blog#16]
![image](https://user-images.githubusercontent.com/4997466/28562268-27c0fdf2-7154-11e7-91a0-3501b4e03aa2.png)

![image](https://user-images.githubusercontent.com/4997466/28562254-1714a30a-7154-11e7-9534-42e81419fc03.png)

建议修改成 `./static/xx.js` 相对路径就可以修复了：

GitHub Repo 地址: https://github.com/JimmyLv/issues
GitHub Pages 路径：https://jimmylv.github.io/issues/

所以，

- 如果是 `static/xx.js` 最后会变成 `https://jimmylv.github.io/static/xx.js`
- 如果是 `./static/xx.js` 最后才会变成**正确加载**的 `https://jimmylv.github.io/issues/static/xx.js`

**Comment by JimmyLv** [comment]
我已经在我那边修改完毕了，修改很简单我就不来蹭 PR 啦，😂

[issues/index.js at a434180735118aabf707a3b5ef382e17dba4fe51 · JimmyLv/issues](https://github.com/JimmyLv/issues/blob/a434180735118aabf707a3b5ef382e17dba4fe51/config/index.js#L10)

**Comment by bingoogolapple** [comment]
可以了，还加了配置抓取任意指定仓库的 Issue，修改了左侧 Bio 太长的问题
