### ISSUE TITLE
筛选功能无法显示含特殊字符的 Label

### ISSUE THREAD

**Issue by JimmyLv** [bingoogolapple/bga_issue_blog#22]
![image](https://user-images.githubusercontent.com/4997466/29000645-14fbf7b8-7aa4-11e7-86fe-69ffbb6fad24.png)

![image](https://user-images.githubusercontent.com/4997466/29000647-1f5d6d68-7aa4-11e7-805f-282399dc49c5.png)

[JimmyLv's GitHub Issues](https://jimmylv.github.io/issues/#/Blog/BlogList)

**Comment by bingoogolapple** [comment]
@JimmyLv 头像下面 Bio 太长那个也改了
