### ISSUE TITLE
Feature request: integrate with gitalk then no redirect to issue page for comments

### ISSUE THREAD

**Issue by JimmyLv** [bingoogolapple/bga_issue_blog#24]
ref: 

- [gitalk/gitalk: Gitalk is a modern comment component based on Github Issue and Preact.](https://github.com/gitalk/gitalk)
- [Replacing Disqus with Github Comments · Gazoo.vrv](http://donw.io/post/github-comments/)

**Comment by bingoogolapple** [comment]
刚才试了一下
* gittalk 这个库貌似没有支持直接传入 Vue 中通过 ref 获取的 DOM 对象
* 只能接收 id，但 Vue 中不能通过 getElementById 来拿到 DOM 对象

![image](https://user-images.githubusercontent.com/8949716/29242271-575fe50c-7fbc-11e7-9e4e-e4b7adb85d46.png)

我去拉他源码看一下，不晓得你对这个问题有有没有解决方案

**Comment by bingoogolapple** [comment]
我觉得 BGAIssueBlog 里直接用 gitalk 不太好，gitalk 的评论是新建 Issue，并且新加了两个 Label，得花时间研究他的源码，把评论追加到当前 Issue 的后面

**Comment by JimmyLv** [comment]
哇塞！你速度太快了，棒！

**Comment by bingoogolapple** [comment]
后续还有些优化要做，底部评论区的样式及预览功能，这种方式拿到 AccessToken 后，该博客的作者也可以不用到 GitHub 上去创建 Issue 和 Label，任务量好大 => 如果你有空的话欢迎提 PR 😄 

下一步还是评论的预览功能
