### ISSUE TITLE
请问怎么添加友链？

### ISSUE THREAD

**Issue by geekyouth** [bingoogolapple/bga_issue_blog#38]
![image](https://user-images.githubusercontent.com/12899262/45420963-2aa07380-b6be-11e8-8f28-8e890af47c2f.png)
body 里面的app 被封装了，后期维护成本太高了。。。

**Comment by bingoogolapple** [comment]
* 「body 里面的app 被封装了，后期维护成本太高了。。。」

单页应用都是这样的吧

**Comment by bingoogolapple** [comment]
* 在 bga_issue_blog/src/store/account.js 的 thirdPartySite 中添加
![image](https://user-images.githubusercontent.com/8949716/69811673-8e627e00-1229-11ea-9ff1-d1aad0755f1f.png)
![image](https://user-images.githubusercontent.com/8949716/69811731-af2ad380-1229-11ea-980b-a5e75ed4d5e6.png)
